@echo off
echo Der PC wird in ca. 2 Minuten neugestartet, nachdem der Virus beendet wurde.
echo Bitte speichere alle Dateien und schließe alle Anwendungen.
echo Drücke eine beliebige Taste zum Fortfahren.
pause

echo Prozess gestartet...
shutdown /r /t 120 /c "Sobald der Virus beendet wurde, wird der PC neugestartet. Bitte speichere alle Dateien. Powered by: PW2025" /d p:4:1
pause

echo Starte...
color 0C
timeout /T 2 /NOBREAK >nul

echo Initialisiere heuristische Analyse...
timeout /T 2 >nul
echo Lade Modul: DeepThreatScan.dll...
timeout /T 2 >nul
echo Prüfe auf polymorphe Signaturen...
timeout /T 2 >nul
echo Enttarne getarnte Prozesse...
timeout /T 2 >nul
echo Analyse von Rootkit-Aktivitäten gestartet...
timeout /T 2 >nul
echo Verdächtige DLL-Injektion erkannt in explorer.exe...
timeout /T 2 >nul
echo Bereinige Schattenkopien...
timeout /T 2 >nul
echo Wiederherstellungspunkt wird erstellt...
timeout /T 2 >nul
echo Systemzeit wird synchronisiert...
timeout /T 2 >nul
echo DNS-Cache wird geleert...
timeout /T 2 >nul
echo Temporäre Internetdateien werden gelöscht...
timeout /T 2 >nul
echo Überprüfung von Autostart-Einträgen...
timeout /T 2 >nul
echo Verdächtiger Registry-Key entfernt: HKCU\Software\Run\TikTokLoader...
timeout /T 2 >nul
echo Bedrohungscode: 0xC0FFEE42...
timeout /T 2 >nul
echo Status: Bedrohung neutralisiert.
color 0E
timeout /T 2 >nul
echo Sicherheitsstufe zurückgesetzt auf: GRÜN.
timeout /T 2 >nul
echo Starte finale Systembereinigung...
timeout /T 2 >nul
echo Lösche temporäre Bedrohungsfragmente...
timeout /T 2 >nul
echo Abschlussbericht wird generiert...
timeout /T 2 >nul
echo Anti-Virus-Modul [PW2025] erfolgreich abgeschlossen.
timeout /T 2 >nul

echo Fertig.
color 0A
pause
exit